{% set name = "jimtcl" %}
{% set version = "0.82" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/msteveb/jimtcl/archive/refs/tags/{{ version }}.tar.gz
    sha256: e8af929b815e4d30e54ff116b2b933e56c00a02b9110529d1a58660b2469aea7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make                  # [unix]
    - pkg-config            # [unix]
    - m2w64-make            # [win]
    - {{ compiler('m2w64-toolchain') }}             # [win]
    - m2w64-pkg-config      # [win]
    - m2w64-openssl         # [win]
    - m2w64-zlib            # [win]
    - m2-bash               # [win]
    - m2-sed                # [win]
  host:
    - openssl               # [unix]
    - zlib                  # [unix]
    - m2w64-openssl         # [win]
    - m2w64-zlib            # [win]
  run:
    - m2w64-openssl         # [win]
    - m2w64-zlib            # [win]

test:
  commands:
    - jimsh --version

about:
  home: https://jim.tcl.tk/index.html/doc/www/www/
  summary: 'A small footprint implementation of the Tcl programming language'
  description: |
    Jim is an opensource small-footprint implementation of the Tcl programming
    language. It implements a large subset of Tcl and adds new features like
    references with garbage collection, closures, built-in Object Oriented
    Programming system, Functional Programming commands, first-class arrays and
    UTF-8 support. All this with a binary size of about 100-200kB (depending
    upon selected options).
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/msteveb/jimtcl

extra:
  recipe-maintainers:
    - mdekstrand
